### ISSUE TITLE
Add a command to get the user ID

### ISSUE THREAD

**Issue by CapacitorSet** [Telegram-Bot-Node/Nikoro#94]
Basic usage: getting the user id of eg. @rTARS. Of course, this can only work if the bot has ever seen the user in one of its groups. This also raises the issue of privacy: what if the user belongs to a different group? Should his ID still be available for search? And what about users who were previously in the group, but left?

Advanced usage: maybe searching by first name?

**Comment by blackdev1l** [comment]
There's no issue about privacy, because it's public data and if the API can let you know the ID there's no  problem to parse it and use it in my opinion. 

We should collect the id by username, the plugin should be able to log on every entrance the id, first name, username and what's not, however, if a user come back in with a different username / firstname/ it should append it to the first one, so we can have a record of the user and its identities

A basic scenario would be like this: 
- User1 joins
  1. bot get triggered and collects id, username, first name
  2. if you need his id you can just call it via /getID  quoting him or doing /getID `@username`
-  user1 join the group again with different username
  1. bot **appends** his information to the previous one, so you have the records of who he was, this information can be used with other plugins such as a 
     - welcome plugin : _user1 joins the group,_ bot replies with:  user1  joined before as `@firstusername`

Records shouldn't be deleted, nor limitated to search.

**Comment by CapacitorSet** [comment]
The logging infrastructure is already there by the way, it's implemented by the Logger proxy. It just needs a way to access the information.

I agree about the issue of privacy.

**Comment by CapacitorSet** [comment]
Something that came up in chat: an `/ids` command to list the user IDs.

**Comment by FerdinandoLM** [comment]
A working concept could be taken from https://github.com/LucentW/s-uzzbot/blob/master/plugins/why.lua, where the user can reply with "#why" (don't understand the choice of that word for the command tbh), and the bot reply with

ℹ️ User @Sempiternum [0123456]
👍 This ID is nor banned nor superbanned.
